---
title: "Creating Shiny Apps"
author: "Alan Arnholt"
date: "1/4/2018"
output: ioslides_presentation
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Shiny Presentation

This R Markdown presentation is made interactive using Shiny. The viewers of the presentation can change the assumptions underlying what's presented and see the results immediately. 

To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html).

## Interactive Plot

```{r eruptions}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50, 100), selected = 35),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.1, max = 2, value = 1, step = 0.1)
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser eruption duration", col = "pink")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})
```


## Shiny App Template

```{r, eval = FALSE, echo = TRUE}
ui <- fluidPage()

server <- function(input, output) {}

shinyApp(ui = ui, server = server)
```


## My Blank App

```{r, echo = FALSE}
shinyAppDir("BlankApp", 
  options=list(width=300, height = 400)
)
```

## My Basic Layout App Code

```{r, eval = FALSE, echo = TRUE}
ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      numericInput(inputId = "MU", 
                   label = "Mean:", 
                   value = 0, 
                   min = -Inf, 
                   max = Inf),
      numericInput(inputId = "SIGMA", 
                   label = "SD:", 
                   value = 1, 
                   min = 0.0001, 
                   max = Inf),
      numericInput(inputId = "SIMS", 
                   label = "Simulate Values:", 
                   value = 1000, 
                   min = 1, 
                   max = 100000),
```

## Continued

```{r, eval = FALSE, echo = TRUE}
      textInput(inputId = "COLOR", 
                label = "Color:", 
                value = "hotpink")
    ),
    mainPanel(
      plotOutput(outputId = "histo")
    ),
  )
)

server <- function(input, output) {
  output$histo <- renderPlot({
    hist(rnorm(input$SIMS, input$MU, input$SIGMA), 
         main = "Simulated Histogram", 
         xlab = "", col = input$COLOR, breaks = "Scott")
  })
}

shinyApp(ui = ui, server = server)
```

## My Basic Layout App

```{r, echo = FALSE}
shinyAppDir("Basic", 
  options=list(width=300, height = 200)
)
```