---
title: "Day One"
author: "Alan Arnholt"
date: "1/17/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Creating A Data Frame

```{r}
ws <- c(67, 64, 66, 67, 68, 61, 64, 65, 69, 71)
hi <- c(70, 69, 72, 70, 70, 62, 68, 65, 66, 77)
name <- c("Dustin", "Cescily", "Averia", "John", "Carter", "Jaehee",
          "Paige", "Sierra", "Austin", "Lee")
sex <- c("M", "F", "F", "M", "M", "F", "F", "F", "M", "M")
DF <- data.frame(Name = name, WingSpan = ws, HeightIn = hi, Sex = sex)
# Remove individual vectors
rm(ws, hi, sex)
str(DF)
DF$Name <- as.character(DF$Name)
str(DF)
```

## Creating a Scatter Plot

```{r}
library(ggplot2)
ggplot(data = DF, aes(x = HeightIn, y = WingSpan, color = Sex)) +
  geom_point() + 
  geom_smooth(method = "lm") + 
  theme_bw()
```

## Computing Descriptive Statistics

```{r, message = FALSE}
library(dplyr)
Res <- DF %>%
  group_by(Sex) %>%
  summarize(MH = mean(HeightIn), SH = sd(HeightIn))
Res
```

## Showing Tables

```{r}
knitr::kable(Res)
```

```{r}
DT::datatable(Res)
```