---
title: "Assignments STT 5812"
author: "Alan T. Arnholt"
date: 'Last compiled: `r format(Sys.time(), "%B %d, %Y")`'
output: 
  html_document: 
    css: asu.css
    highlight: textmate
    theme: cosmo
---

**Jan 12:**

* Go over syllabus.

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes

* Most will have completed what follows in STT 5811.  

* Sign-up for free accounts on [GitHub](https://github.com) and [Rpubs](https://rpubs.com).

* When you register for a free individual GitHub account, request a [student discount](https://education.github.com) to obtain a few private repositories as well as unlimited public repositories.  Please use something similar to **first_name_last_name** as your username when you register with GitHub.  For example, my username on GitHub is *alanarnholt*. If you have a popular name such as John Smith, you may need to provide some other distinquishing characteristic in your username.  Please use the same **username** for your account on Rpubs. 

* Once you have a GitHub account, send an email to arnholtat@appstate.edu with a Subject line of **STT5812 - GitHub Username**, and tell me in the body of your email your first name, last name, and your GitHub username.  I will then manually add you as a team member to the repository in the STAT-ATA-ASU organization that has your name (**Last_name-First_name**).  This repository will be where you store all of your work for this course.  I will also change your repository to a private repository.

* Watch this [video](https://www.youtube.com/watch?v=ZFaWxxzouCY&list=PLjTlxb-wKvXNSDfcKPFH2gzHGyjpeCZmJ&index=3) which provides some background on asking questions.  This stackoverflow thread details how to create a [minimal R reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example/5963610#5963610). Please read [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html) by Eric Raymond and Rick Moen and heed their advice.

**Jan 14:**

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes

Watch the following Videos:

* [Phillip Guo's Unix-like command line tutorials (Four tutorials about 10 minutes each)](http://www.pgbovine.net/command-line-tutorial.htm)

* [Phillip Guo's Basic Git and Github tutorials (Three tutorials about 10 minutes each)](http://www.pgbovine.net/git-tutorial.htm)

* [Clone a GitHub Repo with RStudio (Video)](https://www.youtube.com/watch?v=YxZ8J2rqhEM) (5:05)

* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.

* Follow the directions from [Jenny Bryan's STAT 545](https://stat545-ubc.github.io/git00_index.html) to [Introduce yourself to Git](https://stat545-ubc.github.io/git04_introduce-self-to-git.html), [Make sure you can communicate with GitHub](https://stat545-ubc.github.io/git05_github-connection.html), [Test drive RStudio and GitHub](https://stat545-ubc.github.io/git07_git-github-rstudio.html), and [Cache your GitHub credentials](https://stat545-ubc.github.io/git06_credential-caching.html).


**Jan 19:**

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes

* [Statistics Review](../../STT3851Spring2016/Rmarkdown/StatReview.html)

* Update README file in private repository

* Use an avatar or picture on your GitHub account



**Jan 21:**

* In class lecture: Review of one and two sample inference, permutation tests, and bootstrap procedures --- take notes

* [Statistics Review](../../STT3851Spring2016/Rmarkdown/StatReview.html)

* Quiz

* Discuss [JSE project](./JSERubric.html)


**Jan 26:**

* Amber - [Handwriting and Gender: A multi-use data set](http://www.amstat.org/publications/jse/v23n1/bradley.pdf)

* Josh - [1993 New Car Data](http://www.amstat.org/publications/jse/v1n1/datasets.lock.html)

* Indy - [What Does It Take to Heat a New Room? Estimating Utility Demand in a Home](http://www.amstat.org/publications/jse/v6n1/datasets.carver.html)

* Stephanie - [Using Cigarette Data for An Introduction to Multiple Regression](http://www.amstat.org/publications/jse/v2n1/datasets.mcintyre.html)

* Sussanah - [Comparing the lifetimes of two brands of batteries](http://www.amstat.org/publications/jse/v21n1/dunn.pdf)

* Huy - [How Much Do Minority Lives Matter?](http://www.amstat.org/publications/jse/v23n2/witmer.pdf)

* Kevin - [OkCupid Data for Introductory Statistics and Data Science Courses](http://www.amstat.org/publications/jse/v23n2/kim.pdf)

**Jan 28:**

* Work Day


**Feb 2:**

* Reproduce [Modified Introduction to R](http://stat-ata-asu.github.io/STT3851Spring2016/Rmarkdown/LabChap2.html) up to but not including the _Additional Graphical and Numerical Summaries_ section.  Submit your html file to [CrowdGrader](https://www.crowdgrader.org/crowdgrader/venues/view_venue/1750) no later than 5 pm, Feb 5.

* [Reading flat files with examples](../Rmarkdown/ImportData.html)

**Feb 4:**

* Reproduce [Modified Introduction to R](http://stat-ata-asu.github.io/STT3851Spring2016/Rmarkdown/LabChap2.html) up to but not including the _Additional Graphical and Numerical Summaries_ section.  Submit your html file to [CrowdGrader](https://www.crowdgrader.org/crowdgrader/venues/view_venue/1750) no later than 5 pm, Feb 5.

* Peer review


**Feb 9:**

* Reproduce [Modified Introduction to R](http://stat-ata-asu.github.io/STT3851Spring2016/Rmarkdown/LabChap2.html).  Submit your html file to [CrowdGrader](https://www.crowdgrader.org/crowdgrader/venues/view_venue/1821) no later than 5 pm, Feb 12.



**Feb 11:**

* Turn in the written (print out) portion of your [JSE project](./JSERubric.html) no later than 5 pm, Feb 12.
* Make a 15 minute appointment to go over your project on Tuesday (Feb 16) available times include 11-12:15 and 4:15-5:45. 

**Feb 16:**

* No formal class - Meet with instructor individually to go over project - Instructor will be in his office during class time

**Feb 18:**

* JSE Presentations 

**Feb 23:**

* JSE Presentations 

**Feb 25:**

* Group 1 Teach Lab 1 (25 minutes)
* Group 2 Teach Lab 1 (25 Minutes)
* Group 3 Teach Lab 1 (25 minutes)

**Mar 1:**

* Group 1 Teach Lab 2 (25 minutes)
* Group 2 Teach Lab 2 (25 Minutes)
* Group 3 Teach Lab 2 (25 minutes)

**Mar 3:**

* Lab discussions

**~~Mar 7 - Mar 11~~ **No Class - Spring Break**

**Mar 15:**


* Read pages 59-119 of [ISLR](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)
* Watch [Simple Linear Regression and Confidence Intervals](https://www.youtube.com/watch?v=PsE9UqoWtS4) (13:01)
* Watch [Hypothesis Testing ](https://www.youtube.com/watch?v=J6AdoiNUyWI) (8:24)
* Watch [Multiple Linear Regression and Interpreting Regression Coefficients ](https://www.youtube.com/watch?v=1hbCJyM9ccs) (15:38)
* [Review this document](../Rmarkdown/Chap2Slides.html)
* Work on Chapter 3 Assessment - due no later than 10am March 18, 2016 - The Chapter 3 Assessment will be recorded as both a quiz grade and a midterm grade. 


**Mar 17:**

* Review as needed pages 59-119 of [ISLR](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf)
* Watch [Model Selection and Qualitative Predictors](https://www.youtube.com/watch?v=3T6RXmIHbJ4) (14:51)
* Watch [Interactions and Nonlinearity](https://www.youtube.com/watch?v=IFzVxLv0TKQ) (14:16)
* Watch [Lab: Linear Regression](https://www.youtube.com/watch?v=5ONFqIk3RFg) (22:10)
* Work on Chapter 3 Assessment - due no later than 10am March 18, 2016

**Mar 22:**

* Assign JSE Talks
* Go over Chapter 3 Assessment
* [Cross Validation Hand Out](../../STT3851Spring2016/Rmarkdown/Cross-ValidationInClassHO.pdf)

Watch the following videos:

* [Estimating Prediction Error and Validation Set Approach](https://www.youtube.com/watch?v=_2ij6eaaSl0) (14:01)
* [K-fold Cross-Validation](https://www.youtube.com/watch?v=nZAM5OXrktY) (13:33)


**Mar 24:**

* JSE Talks
* [Cross Validation Hand Out](../../STT3851Spring2016/Rmarkdown/Cross-ValidationInClassHO.pdf)

Watch the following videos:

* [Cross-Validation: The Right and Wrong Ways](https://www.youtube.com/watch?v=S06JpVoNaA0) (10:07)
* [Watch: Lab: Cross-Validation](https://www.youtube.com/watch?v=6dSXlqHAoMk) (11:21)


**~~Mar 29~~ No Class**

**Mar 31:**

* JSE Talks
* Place materials (Solution to Project, Lab Activity with Key, Presentation Slides) 
in the ["JSE-Materials" repository](https://github.com/STAT-ATA-ASU/JSE-Materials).  All class members have read and write permission to this private repository.
* [Reproduce _Lab: Cross-Validation_](../../STT3851Spring2016/Rmarkdown/LabCrossValidation.html). Submit to [CrowdGrader](	https://www.crowdgrader.org/crowdgrader/venues/view_venue/1991) NLT 5:00 PM Friday (2/8/2016).

**Apr 5:**

Start Project 2 - Due NLT 10 am, April 22

* [Example Template Directory](https://github.com/STAT-ATA-ASU/STT3851Spring2016/blob/gh-pages/BDbetaTemplate)
* Use the [housedata.csv](https://github.com/STAT-ATA-ASU/STT3851Spring2016/raw/gh-pages/Data/housedata.csv) file - See [King County Housing Data](http://stat-ata-asu.github.io/STT3851Spring2016/Rmarkdown/KingCounty.html)
* ~~Develop a second Lab Activity - Add written activity to ["JSE-Materials" repository](https://github.com/STAT-ATA-ASU/JSE-Materials)~~
* [Bias Variance Trade-Off](../../STT3851Spring2016/Rmarkdown/BiasVariance.html)

**Apr 7:**

* [Notes on Credit Problem](../../STT3851Spring2016/Rmarkdown/CreditProblemMore.html)

Watch videos:

* [Linear Model Selection and Best Subset Selection](https://www.youtube.com/watch?v=91si52nk3LA) (13:44)
* [Forward Stepwise Selection](https://www.youtube.com/watch?v=nLpJd_iKmrE) (12:26)
* [Backward Stepwise Selection ](https://www.youtube.com/watch?v=NJhMSpI2Uj8) (5:26)
* [Estimating Test Error Using Mallow’s Cp, AIC, BIC, Adjusted R-squared](https://www.youtube.com/watch?v=LkifE44myLc) (14:06)
* [Reproduce _Lab: Cross-Validation_](../../STT3851Spring2016/Rmarkdown/LabCrossValidation.html). Submit to [CrowdGrader](	https://www.crowdgrader.org/crowdgrader/venues/view_venue/1991) NLT 5:00 PM Friday (2/8/2016).
* Quiz - Section 6.1 ISLR

**Apr 12:**

* Using [Book Down](https://bookdown.org/yihui/bookdown/)
* [Example Template Directory](https://github.com/STAT-ATA-ASU/STT3851Spring2016/blob/gh-pages/BDbetaTemplate)
* [Example Paper](../../STT3851Spring2016/BDbetaTemplate/MoreTemplates/main.html)
* Use the [housedata.csv](https://github.com/STAT-ATA-ASU/STT3851Spring2016/raw/gh-pages/Data/housedata.csv) file - See [King County Housing Data](http://stat-ata-asu.github.io/STT3851Spring2016/Rmarkdown/KingCounty.html)

Watch videos:

* [Estimating Test Error Using Cross-Validation](https://www.youtube.com/watch?v=3p9JNaJCOb4) (8:43)
* [Shrinkage Methods and Ridge Regression](https://www.youtube.com/watch?v=cSKzqb0EKS0) (12:37)
* [The Lasso](https://www.youtube.com/watch?v=A5I1G1MfUmA) (15:21)
* [Tuning Parameter Selection for Ridge Regression and Lasso](https://www.youtube.com/watch?v=xMKVUstjXBE) (5:27)

**Apr 14:**

Watch Videos:

* [Dimension Reduction](https://www.youtube.com/watch?v=QlyROnAjnEk) (4:45)
* [Principal Components Regression and Partial Least Squares ](https://www.youtube.com/watch?v=eYxwWGJcOfw) (15:48)
* [Lab: Best Subset Selection](https://www.youtube.com/watch?v=3kwdDGnV8MM) (10:36)
* [Lab: Forward Stepwise Selection and Model Selection Using Validation Set](https://www.youtube.com/watch?v=mv-vdysZIb4) (10:32)
* [Lab: Model Selection Using Cross-Validation](https://www.youtube.com/watch?v=F8MMHCCoALU) (5:32)


**Apr 19:**

Watch Videos:

* [Lab: Ridge Regression and Lasso ](https://www.youtube.com/watch?v=1REe3qSotx8) (16:34)


**Apr 21:**

* Turn in Project 2 - NLT April 22, 10 am
* [CrowdGrader link](	https://www.crowdgrader.org/crowdgrader/venues/view_venue/2028)
* Make sure a single `.Rmd` with the sections outlined in the [Example Paper](../../STT3851Spring2016/BDbetaTemplate/MoreTemplates/main.html) is in your `Project2` directory under your private course repository.  This is 10% of the assignment grade.
* Send an email to the instructor using a subject of "House Data Predictions" with an attached vector (csv file) of your predictions using the data set `housedataTEST.csv`.  Note: your vector should contain 4229 predictions. 


**Apr 26:**

* [Poster Template Directory](https://github.com/STAT-ATA-ASU/STT3851Spring2016/tree/gh-pages/Poster)
* Work on Poster


**Apr 28:**

* Work on Poster

**May 3:**

* Work on Poster

**May 12:**

* Present Group Poster 12-2:30

***

#[Home Page](http://stat-ata-asu.github.io/STT5812CourseRepo/) -       [Syllabus](http://stat-ata-asu.github.io/STT5812CourseRepo/Syllabus/STT5812SyllabusSpring2016.html) - [piazza](https://piazza.com/class/ij30sna9alj1pq)
